---
- name: Prepare
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
        executable: pip3
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      register: result
      until: result is success
      retries: 5
      delay: 5
  roles:
    - calvinbui.ansible_pip
